"""Fifty QA pairs used by the RAG and RAGAS lab steps."""

QA_PAIRS = [
    {"question": "What are the three main types of machine learning?", "reference": "The three main types of machine learning are supervised learning, unsupervised learning, and reinforcement learning."},
    {"question": "What is overfitting in machine learning?", "reference": "Overfitting occurs when a model learns the training data too well, including noise, leading to poor generalization on new data."},
    {"question": "Explain the bias-variance tradeoff.", "reference": "High bias means underfitting; high variance means overfitting. The optimal model balances both to minimize total error."},
    {"question": "How does regularization prevent overfitting?", "reference": "L1 and L2 regularization add penalty terms to the loss function to discourage overly complex models."},
    {"question": "What is cross-validation?", "reference": "Cross-validation splits data into multiple folds to estimate model performance more reliably."},
    {"question": "What is backpropagation?", "reference": "Backpropagation computes gradients of the loss with respect to each weight by applying the chain rule of calculus."},
    {"question": "What are Convolutional Neural Networks primarily used for?", "reference": "Convolutional Neural Networks are primarily used for grid-like data such as images, where local spatial patterns matter."},
    {"question": "How do LSTM networks address the vanishing gradient problem?", "reference": "LSTMs use gates and a cell state to control information flow, helping gradients travel across longer sequences."},
    {"question": "What activation functions are commonly used in neural networks?", "reference": "Common activation functions include ReLU, sigmoid, tanh, and variants such as GELU or Leaky ReLU."},
    {"question": "What is the role of pooling layers in CNNs?", "reference": "Pooling layers reduce spatial dimensions, lower computation, and preserve the strongest local features."},
    {"question": "What is the transformer architecture?", "reference": "The transformer is a neural architecture based on self-attention that processes sequences in parallel and was introduced in Attention Is All You Need in 2017."},
    {"question": "What are word embeddings?", "reference": "Word embeddings represent words as dense vectors where semantically similar words are close in vector space."},
    {"question": "What is transfer learning in NLP?", "reference": "Transfer learning in NLP pre-trains large models on broad corpora and then fine-tunes them for downstream tasks."},
    {"question": "How does BERT handle language understanding?", "reference": "BERT uses bidirectional transformer training with masked language modeling and next sentence prediction objectives."},
    {"question": "What is self-attention in transformers?", "reference": "Self-attention lets each token weigh the relevance of other tokens in the same sequence."},
    {"question": "What is GPT and how is it trained?", "reference": "GPT is an autoregressive transformer trained to predict the next token from previous tokens across large text datasets."},
    {"question": "What is instruction tuning?", "reference": "Instruction tuning fine-tunes a pre-trained model on instruction-following examples so it better follows user intent."},
    {"question": "What is RLHF?", "reference": "Reinforcement Learning from Human Feedback uses human preference data to align model behavior with helpful and safe outputs."},
    {"question": "What is chain-of-thought prompting?", "reference": "Chain-of-thought prompting encourages a model to reason step by step for complex tasks."},
    {"question": "What is the context length of GPT-4?", "reference": "GPT-4 variants support different context windows; some versions support up to 128K tokens."},
    {"question": "What is Retrieval-Augmented Generation?", "reference": "Retrieval-Augmented Generation combines an LLM with retrieval from external knowledge so answers are grounded in relevant documents."},
    {"question": "What are the main components of a RAG pipeline?", "reference": "A RAG pipeline usually includes a document loader, splitter, embedding model, vector store, retriever, prompt, LLM, and output parser."},
    {"question": "What is dense retrieval?", "reference": "Dense retrieval encodes queries and documents as embeddings and ranks relevance by vector similarity."},
    {"question": "Why is chunking strategy important in RAG?", "reference": "Chunking controls what text is retrieved, affecting precision, recall, and whether evidence fits inside the model context window."},
    {"question": "What advanced RAG techniques exist beyond basic retrieval?", "reference": "Advanced RAG techniques include re-ranking, query expansion, HyDE, iterative retrieval, and multi-hop retrieval."},
    {"question": "What are vector databases used for?", "reference": "Vector databases store embeddings and support fast similarity search over high-dimensional vectors."},
    {"question": "What is FAISS?", "reference": "FAISS is a library from Meta AI for efficient similarity search and clustering over dense vectors."},
    {"question": "How do text embeddings capture semantic meaning?", "reference": "Text embeddings map text into numerical vectors so semantically similar texts are placed close together."},
    {"question": "What is HNSW?", "reference": "HNSW is an approximate nearest neighbor algorithm that uses a hierarchical small-world graph for efficient vector search."},
    {"question": "What is hybrid search in vector databases?", "reference": "Hybrid search combines dense vector retrieval with sparse keyword retrieval such as BM25, often merging results with reciprocal rank fusion."},
    {"question": "What is LangChain?", "reference": "LangChain is an open-source framework for building LLM applications with components for prompts, chains, agents, tools, retrievers, and data connections."},
    {"question": "What is LangChain Expression Language (LCEL)?", "reference": "LCEL is a declarative way to compose LangChain runnables with the pipe operator, supporting streaming, async, and batching."},
    {"question": "What is LangGraph?", "reference": "LangGraph extends LangChain for stateful multi-actor workflows modeled as graphs that can include cycles."},
    {"question": "What memory types does LangChain support?", "reference": "LangChain memory patterns include buffer memory, summary memory, window memory, entity memory, and vector store memory."},
    {"question": "What are LangChain retrievers?", "reference": "LangChain retrievers fetch relevant documents for a query from sources such as vector stores, BM25 indexes, or external search systems."},
    {"question": "What is LangSmith?", "reference": "LangSmith is a platform for debugging, tracing, evaluating, and monitoring LLM applications."},
    {"question": "What information do LangSmith traces capture?", "reference": "LangSmith traces capture inputs, outputs, latency, errors, token usage, and nested component runs."},
    {"question": "What is the LangSmith Prompt Hub?", "reference": "LangSmith Prompt Hub stores, versions, and shares prompt templates for reuse, testing, A/B routing, and rollback."},
    {"question": "How does LangSmith help monitor production LLM applications?", "reference": "LangSmith monitors production LLM apps with traces, latency statistics, error rates, feedback, token usage, and evaluation results."},
    {"question": "What are LangSmith datasets used for?", "reference": "LangSmith datasets store examples with inputs and expected outputs for systematic testing and comparison."},
    {"question": "What is RAGAS?", "reference": "RAGAS is an evaluation framework for RAG systems with metrics for faithfulness, answer relevancy, context recall, and context precision."},
    {"question": "How does RAGAS compute faithfulness?", "reference": "RAGAS faithfulness checks whether claims in the answer are supported by the retrieved context."},
    {"question": "What is answer relevancy in RAGAS?", "reference": "Answer relevancy measures how directly the answer addresses the user's question."},
    {"question": "What is context recall in RAGAS?", "reference": "Context recall measures whether the retrieved contexts contain the information needed to answer according to the reference answer."},
    {"question": "What inputs does RAGAS evaluation require?", "reference": "RAGAS evaluation needs user questions, generated answers, retrieved contexts, and often reference answers."},
    {"question": "What is Guardrails AI?", "reference": "Guardrails AI is a framework for validating, correcting, and constraining LLM outputs using validators and on-fail actions."},
    {"question": "What is PII and why is it important to detect in LLM responses?", "reference": "PII is personally identifiable information; detecting it prevents privacy leaks and compliance violations."},
    {"question": "What does structured output validation ensure?", "reference": "Structured output validation ensures model responses conform to a required format or schema such as valid JSON."},
    {"question": "What is Constitutional AI?", "reference": "Constitutional AI guides model behavior using written principles and self-critique instead of relying only on human feedback labels."},
    {"question": "What are common AI safety concerns with LLMs?", "reference": "Common AI safety concerns include hallucination, toxicity, bias, PII leakage, insecure tool use, and jailbreak attacks."},
]

SAMPLE_QUESTIONS = [item["question"] for item in QA_PAIRS]

